theme: jekyll-theme-cayman
title: DSAL Learning Zone
description: Welcome to the DSAL Learning Zone
show_downloads: false

# Add these image configuration parameters:
profile_image:
  enabled: true
  path: "/assets/images/GitHub Cover 2.png"  # Update this to your actual image path
  alt: "Ahmad Salehi"
  width: "200px"
  class: "profile-pic"  # For CSS styling
  style: "float: right; border-radius: 50%; margin: 20px; border: 2px solid #2c3e50;"
